name: 'Deploy Nginx Ingress Controller'
description: "Deploys an Nginx Ingress Controller to a K8s cluster"
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/install-kubectl.sh
      shell: bash
    - run: ${{ github.action_path }}/install-nginx-ingress-controller.sh
      shell: bash